version: '3.3'
services:
  database:
    image: mariadb:10.2.8
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: bind
        source: ./ms_phpbb3.2_barebones.sql
        target: /docker-entrypoint-initdb.d/ms_phpbb3.2_barebones.sql
        read_only: true
  web:
    build: .
    ports:
      - 80:80
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./dev/
        target: /mnt/dev/
