version: '3.3'
services:
  test_database:
    image: mafiascum/forum-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: password

  test:
    image: mafiascum/forum-tester:latest
    depends_on:
      - test_database
    env_file:
      - test.env
    volumes:
      - ./dev/:/var/www/html/phpbb/phpBB/ext/mafiascum/