version: '3.3'
services:
  database:
    image: mafiascum/forum-db:skeleton
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password
      
  web:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./dev/:/mnt/dev/
      - ./dev-styles/:/opt/dev-styles/

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    env_file:
      - .env
