version: '3.3'
services:
  database:
    image: mafiascum/forum-db:skeleton
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: password

  sphinx:
    build: ./sphinx
    depends_on:
      - database
    env_file:
      - .env
    environment:
      SPHINX_MODE: indexing
      
  web:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./dev/:/mnt/dev/
      - ./dev-styles/:/opt/dev-styles/

  api:
    image: mafiascum/api-gateway:latest
    depends_on:
      - database
    env_file:
      - .env
    command: ["watch"]

  sitechat:
    image: mafiascum/site-chat-server
    depends_on:
      - database
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
      - api
      - sitechat
    env_file:
      - .env
