version: '3.3'
services:
  database:
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ms_phpbb3
      MYSQL_ROOT_PASSWORD: password

  sphinx:
    build: ./sphinx
    depends_on:
      - database
    env_file:
      - .env
    environment:
      SPHINX_MODE: indexing
      
  web:
    build: .
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./dev/:/mnt/dev/
      - ./dev-styles/:/opt/dev-styles/
      - web-files:/var/www/html/files
      - web-images:/var/www/html/images
      - web-store:/var/www/html/store
      - web-meta:/var/www/html/meta

  api:
    image: mafiascum/api-gateway:latest
    depends_on:
      - database
    env_file:
      - .env
    command: ["watch"]

  sitechat:
    image: mafiascum/site-chat-server
    depends_on:
      - database
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - web
      - api
      - sitechat
    env_file:
      - .env
      
volumes:
  web-files:
    driver: local
  web-images:
    driver: local
  web-store:
    driver: local
  web-meta:
    driver: local

